name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools flake8 pytest==5.4.3 pytest-asyncio==0.12.0 pytest-timeout==1.3.3
    - name: Lint with flake8
      run: |
        flake8 . --count --max-complexity=6 --max-line-length=127 --show-source --statistics
    - name: Test with pytest
      run: |
        python -m setup install
        cd tests
        pytest
